@echo off
echo Running Kafka Consumer...
go run cmd\kafka-consumer\main.go

echo Running Decision Engine...
go run cmd\engine\main.go

@REM echo Running Tests...
@REM go test ./...

echo Generating Test Bid Data...
go run scripts\generate_bids.go

echo All tasks completed.
pause
