global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'engine'
    static_configs:
      - targets: ['host.docker.internal:2113']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s

  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['host.docker.internal:2112']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s